### ISSUE TITLE
Requirements / Setup

### ISSUE THREAD

**Issue by markamccorkle** [chemerisuk/cordova-plugin-firebase-crash#14]
I assume this plugin needs both `GoogleService-Info.plist` and `google-services.json `in the root of your project? Did I miss the documentation for this somewhere? Does the plugin require any dependencies such as `cordova-support-google-services`? I've tried installing it by assuming the previously mentioned files need to be in the root of the ionic/cordova project but I'm still not seeing anything on my fabric dashboard.

**Comment by amymarsh4work** [comment]
@MarkAMcCorkle cordova-support-google-services is a dependency of this plugin. You can see that by looking at the plugin.xml file in this repo. It should however pull that in when you install the plugin. You could verify that by running 'cordova plugin list' in the root of your project. It should exist in both your package.json and config.xml with the same version if it was installed properly. I mention this because after uninstalling and reinstalling various plugins to get things to work, mine got out of whack and had different versions. 

It makes sense that GoogleService-Info.plist and google-services.json need to be included - but cannot verify for certain this plugin requires them.

**Comment by RTK** [comment]
> I assume this plugin needs both `GoogleService-Info.plist` and `google-services.json `in the root of your project? Did I miss the documentation for this somewhere? Does the plugin require any dependencies such as `cordova-support-google-services`? I've tried installing it by assuming the previously mentioned files need to be in the root of the ionic/cordova project but I'm still not seeing anything on my fabric dashboard.

As stated in the readme of https://github.com/chemerisuk/cordova-support-google-services your services files (.plist and .json) don't need to be placed in your root directory. Put them anywhere you want, but you have to reference those files in your config.xml via <resource-file tag (look at the readme.md file). After each prepare / before a build those files should be ported to the correct folders.  They will be overwritten each time you prepare/build/whatever build step prepares.

To verify:

Android:
platforms/android/src/app/google-services.json

iOS:
platforms/ios/{PROJECT_NAME}/Google-Services.plist
